### ISSUE TITLE
32bit float comparison less_equal gives wrong result

### ISSUE THREAD

**Issue by milokhiggins** [hanmangokiwi/Hmmm#40]
I was comparing a value against 1.0, and it seemed to think that 1.99 <= 1.0 is true. Note that the plain less than works fine, so 1.99 < 1.0 return false. Also values bigger than 2.0 gave the correct result e.g. 2.001 <= 1.0 returns false.

Example function showing the incorrect result:
```mcfunction
# input second value B = 1 
scoreboard players set P0 io 1
function float:32/decompose/main
scoreboard players operation P3 io = R0 io
scoreboard players operation P4 io = R1 io
scoreboard players operation P5 io = R2 io

# input first float, A = 1.99
scoreboard players set P0 io 1073657938
function float:32/from_int/main
scoreboard players operation P0 io = R0 io
scoreboard players operation P1 io = R1 io
scoreboard players operation P2 io = R2 io

# compare values, is A <= B?
function float:32/compare/less_equal/main
tellraw @p [{"text":"1.99 <= 1.00? result = "},{"score":{"name":"R0","objective":"io"}}]
```

**Comment by hanmindev** [comment]
Hi, could you try swapping the decompose and from_int functions? At the moment you are trying to compare

1073657938 <= 1.40129846432e-45

Obviously the answer should still be false but I feel like this might be an edge case since one of the numbers is the smallest float value.

I think once you swap the functions it should work, although I definitely will look into fixing this.

**Comment by milokhiggins** [comment]
Yep, same issue with decompose and from_int swapped.
Sorry, that was my mistake, I meant it to be B set via from_int and A via decompose.

**Comment by hanmindev** [comment]
I will take a look at it, but probably not for a couple of weeks because it's finals season. In the meantime, if you want you can see if you can fix it yourself and submit a pull request.
